configProperties:
  version: v2

application:
  name: istio
  services:
    - name: istio-ingressgateway
      serviceType: deployment
      containers:
        - name: istio-proxy
          hub:
            image: docker.io/istio/proxyv2:1.11.2
          dev:
            gitUrl: https://github.com/istio/istio.git
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            workDir: /home/nocalhost-dev-hub-01
            shell: "/bin/zsh"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - "./build"
            command:
              run: [ "./run.sh" ]
              debug: [ "./debug.sh" ]
            debug:
              remoteDebugPort: 2345
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
            portForward:
              - 15021:15021
              - 8080:8080
              - 8443:8443
              - 31400:31400
              - 15443:15443
              - 15090:15090
    - name: istio-egressgateway
      serviceType: deployment
      containers:
        - name: istio-proxy
          hub:
            image: docker.io/istio/proxyv2:1.11.2
          dev:
            gitUrl: https://github.com/istio/istio.git
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            workDir: /home/nocalhost-dev-hub-01
            shell: "/bin/zsh"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - "./build"
            command:
              run: [ "./run.sh" ]
              debug: [ "./debug.sh" ]
            debug:
              remoteDebugPort: 2345
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
            portForward:
              - 8080:8080
              - 8443:8443
              - 15090:15090
    - name: istiod
      serviceType: deployment
      containers:
        - name: discovery
          hub:
            image: docker.io/istio/pilot:1.11.2
          dev:
            gitUrl: https://github.com/istio/istio.git
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            workDir: /home/nocalhost-dev-hub-01
            shell: "/bin/zsh"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - "./build"
            command:
              run: [ "./run.sh" ]
              debug: [ "./debug.sh" ]
            debug:
              remoteDebugPort: 2345
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
            portForward:
              - 8080:8080
              - 15010:15010
              - 15017:15017