configProperties:
  version: v2

application:
  name: istio
  services:
    - name: istiod
      serviceType: deployment
      containers:
        - name: discovery
          hub:
            image: docker.io/istio/pilot:1.11.2
          dev:
            gitUrl: https://github.com/istio/istio.git
            image: nocalhost-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            workDir: /home/nocalhost-dev-hub-01
            shell: "/bin/zsh"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - "./build"
            command:
              run:
                - go
                - env
                - -w
                - GOPROXY=https://goproxy.cn,direct
                - '&&'
                - go
                - run
                - pilot/cmd/pilot-discovery/main.go
                - discovery
                - --monitoringAddr=:15014
                - --log_output_level=default:info
                - --domain cluster.local
                - --keepaliveMaxServerConnectionAge 30m
              debug:
                - go env -w GOPROXY=https://goproxy.cn,direct
                - '&&'
                - GOARCH=amd64 CGO_ENABLED=0 go build -o main -gcflags "all=-N -l" istio.io/istio/pilot/cmd/pilot-discovery
                - '&&'
                - dlv
                - --headless
                - --log
                - --listen :2345
                - --api-version 2
                - --accept-multiclient
                - exec ./main discovery -- --monitoringAddr=:15014 --log_output_level=default:info --domain=cluster.local --keepaliveMaxServerConnectionAge=30m
            debug:
              remoteDebugPort: 2345
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
            portForward:
              - 8080:8080
              - 15010:15010
              - 15017:15017