configProperties:
  version: v2

application:
  name: nocalhost

  services:
    - name: nocalhost-api
      serviceType: deployment
      containers:
        - name: nocalhost-api
          hub:
            image: nocalhost-api
          dev:
            gitUrl: https://github.com/nocalhost/nocalhost.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:zsh
            workDir: /home/nocalhost-dev
            shell: "/bin/zsh"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - "./build"
            command:
              build: [ "make", "api" ]
              run: [ "make", "api", "&&", "./build/nocalhost-api", "-c", "/app/config/config.yaml" ]
              debug: [ "make", "api", "&&", "dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "./build/nocalhost-api", "--", "-c", "/app/config/config.yaml" ]
            debug:
              remoteDebugPort: 2345
            env:
              - name: NOCALHOST_INJECT_DEV_ENV
                value: WHATEVER
            portForward:
              - 8080:8080


    - name: nocalhost-web
      serviceType: deployment
      containers:
        - name: nocalhost-web
          hub:
            image: nocalhost-web
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/nocalhost-web.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
            workDir: /home/nocalhost-dev
            shell: "bash"
            sync:
              type: send
              filePattern:
                - .
              ignoreFilePattern:
                - ".git"
                - ".github"
                - ".vscode"
                - "node_modules"
            portForward:
              - 80:80
            resources:
              limits:
                cpu: "0.3"
                memory: 200Mi
              requests:
                cpu: "0.1"
                memory: 100Mi
