configProperties:
  version: v2

application:
  name: bookinfo
  services:
    - name: productpage
      serviceType: deployment
      containers:
        - name: productpage
          hub:
            image: productpage
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-productpage.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/python:3.7.7-slim-productpage
            shell: bash
            workDir: /home/nocalhost-dev-hub
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
                - ".idea"
            portForward:
              - 39080:9080
    - name: details
      serviceType: deployment
      containers:
        - name: details
          hub:
            image: details
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-details.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/ruby:2.7.1-slim
            shell: bash
            workDir: /home/nocalhost-dev-hub
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
            env: 
            - name: DEBUG
              value: "true"
    - name: ratings
      serviceType: deployment
      containers:
        - name: ratings
          hub:
            image: ratings
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-ratings.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/node:12.18.1-slim
            shell: bash
            workDir: /home/nocalhost-dev-hub
            command:
              build: []
              run:
                - node
                - ratings.js
              debug:
                - npm
                - install
                - "&&"
                - node
                - --inspect-brk
                - ratings.js
              hotReloadRun: []
              hotReloadDebug: []
            debug:
              remoteDebugPort: 9229
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
                - "node_modules"
            env: 
            - name: DEBUG
              value: "true"
    - name: reviews
      serviceType: deployment
      containers:
        - name: reviews
          hub:
            image: reviews
          dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-reviews.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/java:latest
            shell: bash
            workDir: /home/nocalhost-dev-hub
            command:
              build: [ "./gradlew", "build" ]
              run: [ "./gradlew", "bootRun" ]
              debug: [ "./gradlew", "bootRun", "--debug-jvm" ]
            debug:
              remoteDebugPort: 5005
            sync: 
              type: send
              filePattern: 
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
                - ".gradle"
                - "build"
    - name: authors
      serviceType: deployment
      containers:
        - dev:
            gitUrl: https://e.coding.net/codingcorp/nocalhost/bookinfo-authors.git
            image: codingcorp-docker.pkg.coding.net/nocalhost/dev-images/golang:latest
            shell: sh
            workDir: /home/nocalhost-dev
            command:
              run: [ "./run.sh" ]
              debug: [ "./debug.sh" ]
            debug:
              remoteDebugPort: 9009
            sync:
              type: send
              filePattern:
                - ./
              ignoreFilePattern:
                - ".git"
                - ".github"
